name: CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Install Catch2
        run: |
          cd /tmp
          git clone https://github.com/catchorg/Catch2
          cd Catch2
          mkdir build && cd build
          cmake ..
          make
          sudo make install
      - name: Checkout source
        uses: actions/checkout@v2
      - name: Build
        run: |
          cd $GITHUB_WORKSPACE
          mkdir build && cd build
          cmake ..
          make
      - name: Test
        run: |
          cd build
          make test